apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-java-maven-app
  labels:
    app: simple-java-maven-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-java-maven-app
  template:
    metadata:
      labels:simple-java-maven-appreviews
    spec:
      containers:
      - name: simple-java-maven-app
        image: registry2.daocloud.cn:30842/bookinfo/simple-java-maven-app:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        command:
        - sleep
        args:
        - 99d
